# Opt algo visualizer

This notebook reads the pickle produced by `tests.py` and visualizes it

In [362]:
import matplotlib.pyplot as plt
import seaborn as sns
import pickle

In [363]:
out = pickle.load(open('tests.pickle', 'rb'))
out.keys()
out[('DataModel', 'RandomSearch')][2]

z      func                                            history  \
0   196  0.858549  [[1, 2.785028378508035], [2, 2.466836378732150...   
1   196  1.031117  [[1, 2.7386057564942563], [2, 2.43320711714759...   
2   196  0.934322  [[1, 2.883269417982422], [2, 2.572360313057610...   
3   196  0.907494  [[1, 2.5165147925721314], [2, 2.04901376613061...   
4   196  0.925906  [[1, 2.609985881212644], [2, 2.281984627446307...   
5   196  0.881768  [[1, 2.652105398644376], [2, 2.312448270156349...   
6   196  0.873222  [[1, 2.753565717481991], [2, 2.421835176403153...   
7   196  0.906387  [[1, 2.794557198118331], [2, 2.464302787092118...   
8   196  0.890382  [[1, 2.792840645745612], [2, 2.470964153499981...   
9   196  0.930053  [[1, 2.797336111514382], [2, 2.470281615414166...   
10  196  0.921870  [[1, 2.795767358792104], [2, 2.461026580949556...   
11  196  0.894314  [[1, 2.6691987140182656], [2, 2.27589462859002...   
12  196  0.943277  [[1, 2.9260619079345886], [2, 2.61005528988826...   
13  196  0.902055  [[1, 2.5990635220410514], [2, 2.23418981341348...   
14  196  0.946166  [[1, 2.682037569209661], [2, 2.357119927092690...   
15  196  0.932012  [[1, 2.903706248416241], [2, 2.565549863813707...   
16  196  0.879038  [[1, 2.2590527009404475], [2, 1.78318171730173...   
17  196  0.934181  [[1, 2.909792864328665], [2, 2.592239424368496...   
18  196  0.908248  [[1, 2.523444111463864], [2, 2.109296892379642...   
19  196  0.950766  [[1, 2.6130220149948222], [2, 2.29812336938724...   

                                                    x  
0   -0.6913612828995372|2.158247079543714|2.665197...  
1   0.6357676919435882|-1.7992389428405733|-0.6756...  
2   -1.3142581519332552|-0.36939509312370156|-0.10...  
3   0.37357886540853524|-0.17366793602885533|1.133...  
4   2.7622029239195163|2.1488654322907585|-1.14494...  
5   2.7051523660880017|2.848617885514215|-0.308792...  
6   -2.471126667390542|1.7582076549284942|2.538985...  
7   -1.5501528715190434|-0.520925924331026|1.37513...  
8   -0.34179984058574053|0.5903962210879579|-2.236...  
9   -2.457444159226181|-2.2729929744313884|2.95199...  
10  -0.12757431438656486|-0.49377165327191364|-1.2...  
11  -1.49958130054032|-0.34876078037209|0.60760744...  
12  -0.4963580264559009|-1.2555839837650273|1.1359...  
13  1.0209134526381725|0.8639933951253749|0.975052...  
14  0.8161118091035591|-0.25158718455918994|-2.837...  
15  0.8506538809898432|0.2638231836172542|2.805569...  
16  -0.5000622832995227|1.4740116311973352|-2.8039...  
17  0.09658087838462048|-1.2148236242490111|0.2569...  
18  2.2407972120826116|2.1308201282570884|-1.66602...  
19  1.061633539595979|0.06061290831292432|-1.50403...

In [364]:
benchmark_to_plot = 'DataModel'
algo_to_plot      = 'RandomSearch'

The code below will plot the trace for this algorithm and this benchmark. Click on the pan button, and then
  - Left-click and drag to pan
  - Right-click and drag to zoom

In [365]:
import plotly.graph_objects as go

df = out[(benchmark_to_plot, algo_to_plot)][2].copy()
best_obj = out[(benchmark_to_plot, algo_to_plot)][1]

df_exploded = df.explode('history').reset_index(drop=True)
df_exploded['obj'] = df_exploded.history.str[1].astype(float)

# Create figure
fig = go.Figure()

# Add cumulative minimum line
fig.add_trace(
    go.Scatter(
        x=df_exploded.index,
        y=df_exploded.obj.cummin(),
        mode='lines+markers',
        name='Minimum thus far',
        line=dict(color='red', width=2),
        marker=dict(size=6, symbol='circle-open')
    )
)

# Add individual traces for each x value
for this_group, this_df in df_exploded.groupby('x'):
    fig.add_trace(
        go.Scatter(
            x=this_df.index,
            y=this_df.obj,
            mode='lines+markers',
            name=f'x={this_group[:20]}...',
            line=dict(color='black', width=0.3),
            marker=dict(size=4, symbol='x'),
            showlegend=False
        )
    )

# Update layout
fig.update_layout(
    title=f'Connected lines correspond to evaluations<br>for a single value of x at different fidelities<br>(Minimum thus far in red; final minimum: {round(best_obj, 3)})',
    xaxis_title='Function evaluation number',
    yaxis_title='Function value (log scale)',
    yaxis_type='log',
    template='plotly_white',
    showlegend=True,
    width=1000,
    height=600
)

fig.show()

In [366]:
import numpy as np
x,y,history,_ = out[('DataModel', 'SMAC')]
x

print(x)
proportions = np.exp(x) / np.sum(np.exp(x))
print(proportions)
print(y)

[-2.1595209   2.56585878 -2.48474418 -0.52448693  0.43722891]
[0.00751623 0.84763055 0.00542947 0.03855552 0.10086823]
0.8328044470729105


In [367]:
import numpy as np
x,y,history,_ = out[('DataModel', 'RandomSearch')]
x

print(x)
proportions = np.exp(x) / np.sum(np.exp(x))
print(proportions)
print(y)

[-0.69136128  2.15824708  2.66519781  1.21694936  0.80180458]
[0.01719272 0.29710754 0.49326417 0.11590796 0.07652761]
0.8585493788831409


In [368]:
df_exploded = df.explode('history').reset_index(drop=True)
df_exploded[:10]

z      func                   history  \
0  196  0.858549    [1, 2.785028378508035]   
1  196  0.858549   [2, 2.4668363787321503]   
2  196  0.858549    [3, 2.089462225951801]   
3  196  0.858549   [4, 1.7161594169362049]   
4  196  0.858549   [5, 1.5753882989647943]   
5  196  0.858549   [6, 1.4607402151058957]   
6  196  0.858549   [7, 1.3613316954605805]   
7  196  0.858549   [8, 1.2999111782847748]   
8  196  0.858549   [9, 1.2661750112999424]   
9  196  0.858549  [10, 1.2441256685985644]   

                                                   x  
0  -0.6913612828995372|2.158247079543714|2.665197...  
1  -0.6913612828995372|2.158247079543714|2.665197...  
2  -0.6913612828995372|2.158247079543714|2.665197...  
3  -0.6913612828995372|2.158247079543714|2.665197...  
4  -0.6913612828995372|2.158247079543714|2.665197...  
5  -0.6913612828995372|2.158247079543714|2.665197...  
6  -0.6913612828995372|2.158247079543714|2.665197...  
7  -0.6913612828995372|2.158247079543714|2.665197...  
8  -0.6913612828995372|2.158247079543714|2.665197...  
9  -0.6913612828995372|2.158247079543714|2.665197...

In [369]:
final_evals

x   z      func  total_z
0    -0.0948059872192|-0.3493213833927|1.9876634323...   8  1.422342        8
1    -0.2180836506869|-2.4268221506678|-1.188318982...   3  1.342132       11
2    -0.2623764057506|-2.7394914541783|-2.755900857...   3  2.106012       14
3    -0.370065760503|2.6812081810664|-0.12291305782...   8  0.941167       22
4    -0.454158833514|-0.1920745556595|0.49305275487...   3  2.132444       25
..                                                 ...  ..       ...      ...
124  2.832589471368|-1.4559113655566|-1.89068381384...   3  1.890356      773
125  2.8681612865688|1.3154987564365|1.729123041608...  22  1.183719      795
126  2.8806033466499|-1.011569622184|-1.56825364225...  22  1.257306      817
127  2.9017853094703|1.3864382150673|-2.52380525773...   3  1.879156      820
128  2.976517964207|0.9670072039676|1.7291230416088...   3  1.993906      823

[129 rows x 4 columns]

In [370]:
# Create figure
fig = go.Figure()

# Define colors for each algorithm
colors = {
    'SMAC': 'red',
    'RandomSearch': 'blue',
    'GridSearch': 'green'
}

# Plot each algorithm
for algo in ['SMAC', 'RandomSearch', 'GridSearch']:
    # Get data for this algorithm
    df = out[(benchmark_to_plot, algo)][2].copy()
    best_obj = out[(benchmark_to_plot, algo)][1]
    
    df_exploded = df.explode('history').reset_index(drop=True)
    df_exploded['obj'] = df_exploded.history.str[1].astype(float)

    # Add cumulative minimum line
    fig.add_trace(
        go.Scatter(
            x=df_exploded.index,
            y=df_exploded.obj.cummin(),
            mode='lines',  # Removed markers for clarity
            name=f'{algo} (min thus far)',
            line=dict(color=colors[algo], width=2)
        )
    )

    # Add individual traces for each x value
    for this_group, this_df in df_exploded.groupby('x'):
        fig.add_trace(
            go.Scatter(
                x=this_df.index,
                y=this_df.obj,
                mode='lines',  # Removed markers for clarity
                name=f'{algo} x={this_group[:20]}...',
                line=dict(color=colors[algo], width=0.3, dash='dot'),
                showlegend=False
            )
        )

# Update layout
fig.update_layout(
    title='Algorithm Comparison<br>Connected dotted lines correspond to evaluations for a single value of x at different fidelities <br>(1B model size)',
    xaxis_title='Fidelity (Train Steps) Spent',
    yaxis_title='Function value (log scale)',
    yaxis_type='log',
    template='plotly_white', 
    showlegend=True,
    width=1000,
    height=600
)

fig.show()

In [373]:
# Create figure
fig = go.Figure()

# Define colors for each algorithm
colors = {
    'SMAC': 'red',
    'RandomSearch': 'blue',
    'GridSearch': 'green'
}

# Plot each algorithm
for algo in ['SMAC', 'RandomSearch', 'GridSearch']:
    # Get data for this algorithm
    df = out[(benchmark_to_plot, algo)][2].copy()
    best_obj = out[(benchmark_to_plot, algo)][1]
    
    df_exploded = df.explode('history').reset_index(`drop=True)
    df_exploded['obj'] = df_exploded.history.str[1].astype(float)

    # Add cumulative minimum line
    fig.add_trace(
        go.Scatter(
            x=df_exploded.index,
            y=df_exploded.obj.cummin(),
            mode='lines',  # Removed markers for clarity
            name=f'{algo} (min thus far)',
            line=dict(color=colors[algo], width=2)
        )
    )



# Update layout
fig.update_layout(
    title='Algorithm Comparison<br>Connected dotted lines correspond to evaluations for a single value of x at different fidelities <br>(1B model size)',
    xaxis_title='Fidelity (Train Steps) Spent',
    yaxis_title='Function value (log scale)',
    yaxis_type='log',
    template='plotly_white', 
    showlegend=True,
    width=1000,
    height=600
)

fig.show()

In [371]:
import numpy as np
import pandas as pd

benchmark_to_plot = 'DataModel'

# Analysis for each optimizer
for algo in ['SMAC', 'RandomSearch', 'GridSearch']:
    print(f"\n=== Analysis for {algo} ===")
    
    # Get the data
    df = out[(benchmark_to_plot, algo)][2].copy()
    df_exploded = df.explode('history').reset_index(drop=True)
    df_exploded['fidelity'] = df_exploded.history.str[0].astype(float)
    df_exploded['obj'] = df_exploded.history.str[1].astype(float)
    
    # Basic stats
    print(f"Total number of evaluations: {len(df_exploded)}")
    print(f"Total compute cost (sum of fidelities): {df_exploded['fidelity'].sum()}")
    
    # Fidelity distribution
    print("\nFidelity distribution:")
    print(f"Min fidelity: {df_exploded['fidelity'].min()}")
    print(f"Max fidelity: {df_exploded['fidelity'].max()}")
    print(f"Mean fidelity: {df_exploded['fidelity'].mean():.2f}")
    print(f"Median fidelity: {df_exploded['fidelity'].median()}")
    
    # Count evaluations at different fidelity ranges
    fidelity_ranges = [0, 50, 100, 150, 200]
    for i in range(len(fidelity_ranges)-1):
        count = len(df_exploded[(df_exploded['fidelity'] > fidelity_ranges[i]) & 
                               (df_exploded['fidelity'] <= fidelity_ranges[i+1])])
        print(f"Evaluations with fidelity {fidelity_ranges[i]}-{fidelity_ranges[i+1]}: {count}")
    
    # Final performance
    print(f"\nBest objective value found: {df_exploded['obj'].min():.4f}")


=== Analysis for SMAC ===
Total number of evaluations: 3905
Total compute cost (sum of fidelities): 231892.0

Fidelity distribution:
Min fidelity: 1.0
Max fidelity: 196.0
Mean fidelity: 59.38
Median fidelity: 39.0
Evaluations with fidelity 0-50: 2221
Evaluations with fidelity 50-100: 724
Evaluations with fidelity 100-150: 500
Evaluations with fidelity 150-200: 460

Best objective value found: 0.8328

=== Analysis for RandomSearch ===
Total number of evaluations: 3920
Total compute cost (sum of fidelities): 386120.0

Fidelity distribution:
Min fidelity: 1.0
Max fidelity: 196.0
Mean fidelity: 98.50
Median fidelity: 98.5
Evaluations with fidelity 0-50: 1000
Evaluations with fidelity 50-100: 1000
Evaluations with fidelity 100-150: 1000
Evaluations with fidelity 150-200: 920

Best objective value found: 0.8585

=== Analysis for GridSearch ===
Total number of evaluations: 3920
Total compute cost (sum of fidelities): 386120.0

Fidelity distribution:
Min fidelity: 1.0
Max fidelity: 196.0
Mean

In [372]:
import numpy as np
import pandas as pd

benchmark_to_plot = 'DataModel'

def calculate_true_compute(df):
    """Calculate true compute cost accounting for memoization"""
    compute_cost = 0
    seen_configs = {}  # Keep track of configurations we've seen
    
    # Convert x column to string for consistent dictionary keys
    df['x_str'] = df['x'].astype(str)
    
    # Go through each evaluation in order
    for _, row in df.iterrows():
        x_str = row['x_str']
        history = row['history']  # Already a list of [fidelity, value] pairs
        
        if x_str not in seen_configs:
            # New configuration - count all fidelities
            compute_cost += sum(float(h[0]) for h in history)
            seen_configs[x_str] = float(history[-1][0])  # highest fidelity used
        else:
            # Configuration seen before - only count new fidelities
            prev_max_fidelity = seen_configs[x_str]
            new_fidelities = [float(h[0]) for h in history if float(h[0]) > prev_max_fidelity]
            compute_cost += sum(new_fidelities)
            seen_configs[x_str] = max(float(history[-1][0]), prev_max_fidelity)
            
    return compute_cost

# Analysis for each optimizer
for algo in ['SMAC', 'RandomSearch', 'GridSearch']:
    print(f"\n=== Analysis for {algo} ===")
    
    # Get the data
    df = out[(benchmark_to_plot, algo)][2].copy()
    
    # Calculate true compute cost with memoization
    true_compute = calculate_true_compute(df)
    
    # Get evaluation statistics
    df_exploded = df.explode('history').reset_index(drop=True)
    df_exploded['fidelity'] = df_exploded.history.str[0].astype(float)
    df_exploded['obj'] = df_exploded.history.str[1].astype(float)
    
    print(f"Number of unique configurations tested: {len(df['x'].unique())}")
    print(f"Total number of evaluations (including repeated configs): {len(df_exploded)}")
    print(f"True compute cost (accounting for memoization): {true_compute}")
    
    # Fidelity distribution of actual evaluations
    print("\nFidelity distribution of actual evaluations:")
    print(f"Min fidelity: {df_exploded['fidelity'].min()}")
    print(f"Max fidelity: {df_exploded['fidelity'].max()}")
    print(f"Mean fidelity: {df_exploded['fidelity'].mean():.2f}")
    print(f"Median fidelity: {df_exploded['fidelity'].median()}")
    
    # Best performance
    print(f"\nBest objective value found: {df_exploded['obj'].min():.4f}")


=== Analysis for SMAC ===
Number of unique configurations tested: 144
Total number of evaluations (including repeated configs): 3905
True compute cost (accounting for memoization): 231892.0

Fidelity distribution of actual evaluations:
Min fidelity: 1.0
Max fidelity: 196.0
Mean fidelity: 59.38
Median fidelity: 39.0

Best objective value found: 0.8328

=== Analysis for RandomSearch ===
Number of unique configurations tested: 20
Total number of evaluations (including repeated configs): 3920
True compute cost (accounting for memoization): 386120.0

Fidelity distribution of actual evaluations:
Min fidelity: 1.0
Max fidelity: 196.0
Mean fidelity: 98.50
Median fidelity: 98.5

Best objective value found: 0.8585

=== Analysis for GridSearch ===
Number of unique configurations tested: 20
Total number of evaluations (including repeated configs): 3920
True compute cost (accounting for memoization): 386120.0

Fidelity distribution of actual evaluations:
Min fidelity: 1.0
Max fidelity: 196.0
Mean 